/**
 * The webhook verifier is only worth anything if it agrees with the signer, byte for byte.
 *
 * So the bulk of this suite is not hand-written expectations: it is
 * `fixtures/webhook-signature-vectors.json`, generated by running Kaval's PRODUCTION signer
 * (`apps/server/src/webhooks/callback-signing.ts`) over bodies and key generations chosen to pin the
 * parts an independent reimplementation gets wrong — UTF-8 bodies, whitespace the sender did not
 * normalise, a rotation overlap, a sibling subscription's genuinely-signed delivery. The Python SDK
 * runs the same file. Two implementations that both pass it cannot disagree with each other, and
 * neither can drift away from the issuer without this failing.
 *
 * The rest is the framework-shaped surface the vectors cannot express: header bags that are objects
 * versus `.get()` bags, and the caller mistakes that must throw loudly rather than read as a forgery.
 */

import { readFileSync } from "node:fs";
import { describe, expect, test } from "vitest";
import {
  DEFAULT_WEBHOOK_TOLERANCE_SECONDS,
  verifyWebhookSignature,
  WEBHOOK_SIGNED_CONTENT,
  type WebhookRejectionReason,
} from "../../src/verify/index.js";

interface Vector {
  name: string;
  why: string;
  secrets: Record<string, string>;
  body: string;
  headers: Record<string, string>;
  now: number;
  tolerance_seconds: number | null;
  expected: { valid: boolean; reason: WebhookRejectionReason | null };
}

const SUITE = JSON.parse(
  readFileSync(
    new URL(
      "../../../../fixtures/webhook-signature-vectors.json",
      import.meta.url,
    ),
    "utf8",
  ),
) as { signed_content: string; vectors: Vector[] };

function run(vector: Vector) {
  return verifyWebhookSignature({
    body: vector.body,
    headers: vector.headers,
    secrets: vector.secrets,
    toleranceSeconds: vector.tolerance_seconds,
    now: vector.now * 1000,
  });
}

describe("conformance with the issuer's signer", () => {
  test("the fixture is the suite it claims to be", () => {
    // A vector file that silently lost its negative half would still pass every case below.
    expect(SUITE.signed_content).toBe(WEBHOOK_SIGNED_CONTENT);
    expect(SUITE.vectors.length).toBeGreaterThanOrEqual(21);
    expect(
      SUITE.vectors.filter((vector) => vector.expected.valid).length,
    ).toBeGreaterThanOrEqual(8);
    expect(
      SUITE.vectors.filter((vector) => !vector.expected.valid).length,
    ).toBeGreaterThanOrEqual(13);
    expect(new Set(SUITE.vectors.map((vector) => vector.name)).size).toBe(
      SUITE.vectors.length,
    );
  });

  for (const vector of SUITE.vectors) {
    test(`${vector.name} — ${vector.why}`, () => {
      const result = run(vector);
      expect(result.valid).toBe(vector.expected.valid);
      if (result.valid) {
        expect(result.keyId).toBe(vector.headers["webhook-key-id"]);
        expect(result.webhookId).toBe(vector.headers["webhook-id"]);
        expect(Number.isFinite(result.timestamp.getTime())).toBe(true);
      } else {
        expect(result.reason).toBe(vector.expected.reason);
        expect(result.message).not.toContain(Object.values(vector.secrets)[0]);
      }
    });
  }
});

describe("the bytes that were signed", () => {
  const genuine = SUITE.vectors.find(
    (vector) => vector.name === "valid_delta_event",
  )!;

  test("a re-serialised body does not verify, which is why the raw bytes are required", () => {
    // The mistake every webhook integration makes once: `express.json()` on the route, then
    // `JSON.stringify(req.body)` back into the verifier. The parsed object is identical; the bytes
    // are not, and no genuine delivery would ever verify again. Kaval's own bodies come out of
    // `JSON.stringify`, so this uses the vector whose body was NOT spelled that way — an intermediary
    // that pretty-printed, or any future sender that does, is enough to make the difference real.
    const spaced = SUITE.vectors.find(
      (vector) => vector.name === "valid_body_with_incidental_whitespace",
    )!;
    const reserialised = JSON.stringify(JSON.parse(spaced.body));
    expect(reserialised).not.toBe(spaced.body);
    expect(run(spaced).valid).toBe(true);
    expect(run({ ...spaced, body: reserialised }).valid).toBe(false);
  });

  test("raw bytes and the equivalent string are the same input", () => {
    const asBytes = verifyWebhookSignature({
      body: new TextEncoder().encode(genuine.body),
      headers: genuine.headers,
      secrets: genuine.secrets,
      now: genuine.now * 1000,
    });
    expect(asBytes.valid).toBe(true);
    expect(run(genuine).valid).toBe(true);
  });
});

describe("header bags", () => {
  const genuine = SUITE.vectors.find(
    (vector) => vector.name === "valid_minimal",
  )!;

  test("reads a fetch-style bag through .get()", () => {
    const bag = {
      get: (name: string) => genuine.headers[name] ?? null,
    };
    expect(
      verifyWebhookSignature({
        body: genuine.body,
        headers: bag,
        secrets: genuine.secrets,
        now: genuine.now * 1000,
      }).valid,
    ).toBe(true);
  });

  test("reads a plain object whose header names are not lowercased", () => {
    const bag = Object.fromEntries(
      Object.entries(genuine.headers).map(([name, value]) => [
        name.replace(
          /(^|-)([a-z])/gu,
          (_, dash: string, letter: string) => dash + letter.toUpperCase(),
        ),
        value,
      ]),
    );
    expect(Object.keys(bag)).toContain("Webhook-Signature");
    expect(
      verifyWebhookSignature({
        body: genuine.body,
        headers: bag,
        secrets: genuine.secrets,
        now: genuine.now * 1000,
      }).valid,
    ).toBe(true);
  });

  test("refuses a repeated header rather than picking one", () => {
    // Node hands duplicates over as an array (or a ", "-joined string). Either way there are two
    // candidate signed-content strings and no principled way to choose; guessing is how a verifier
    // ends up authenticating an attacker's header.
    const result = verifyWebhookSignature({
      body: genuine.body,
      headers: {
        ...genuine.headers,
        "webhook-id": [genuine.headers["webhook-id"]!, "evt_injected"],
      },
      secrets: genuine.secrets,
      now: genuine.now * 1000,
    });
    expect(result.valid).toBe(false);
    expect(result.valid === false && result.reason).toBe("missing_header");
  });
});

describe("the replay window", () => {
  const genuine = SUITE.vectors.find(
    (vector) => vector.name === "valid_minimal",
  )!;
  const signedAtMs = Number(genuine.headers["webhook-timestamp"]) * 1000;

  test("defaults to five minutes, and the boundary is inclusive", () => {
    expect(DEFAULT_WEBHOOK_TOLERANCE_SECONDS).toBe(300);
    const at = (offsetSeconds: number) =>
      verifyWebhookSignature({
        body: genuine.body,
        headers: genuine.headers,
        secrets: genuine.secrets,
        now: signedAtMs + offsetSeconds * 1000,
      });
    expect(at(DEFAULT_WEBHOOK_TOLERANCE_SECONDS).valid).toBe(true);
    expect(at(DEFAULT_WEBHOOK_TOLERANCE_SECONDS + 1).valid).toBe(false);
    expect(at(-DEFAULT_WEBHOOK_TOLERANCE_SECONDS).valid).toBe(true);
    expect(at(-DEFAULT_WEBHOOK_TOLERANCE_SECONDS - 1).valid).toBe(false);
  });

  test("`now` defaults to the wall clock", () => {
    // Not a tautology: the default has to be read at call time. A module-load `Date.now()` would
    // pass every fixed-`now` test above and then start rejecting live traffic five minutes after
    // the process booted.
    const result = verifyWebhookSignature({
      body: genuine.body,
      headers: genuine.headers,
      secrets: genuine.secrets,
    });
    expect(result.valid).toBe(false);
    expect(result.valid === false && result.reason).toBe(
      "timestamp_out_of_tolerance",
    );
  });
});

describe("the documented example stays true", () => {
  const README = readFileSync(
    new URL("../../README.md", import.meta.url),
    "utf8",
  );

  test("every rejection reason a receiver branches on is documented", () => {
    // The README lists the reasons inline so an integrator can write the switch without opening the
    // types. Renaming one silently is how that list becomes a lie.
    const reasons = new Set(
      SUITE.vectors
        .map((vector) => vector.expected.reason)
        .filter((reason) => reason !== null),
    );
    expect(reasons.size).toBe(7);
    for (const reason of reasons)
      expect(README, `README omits ${reason}`).toContain(reason);
  });

  test("the Express handler reads the raw body", () => {
    // `express.json()` on this route is the one mistake that makes every genuine delivery fail.
    expect(README).toContain('express.raw({ type: "application/json" })');
    expect(README).not.toContain('app.post("/hooks/kaval", express.json()');
  });
});

describe("caller mistakes throw instead of reading as a forgery", () => {
  const genuine = SUITE.vectors.find(
    (vector) => vector.name === "valid_minimal",
  )!;
  const base = {
    body: genuine.body,
    headers: genuine.headers,
    secrets: genuine.secrets,
    now: genuine.now * 1000,
  };

  test("an empty secret map is a configuration bug, not an invalid signature", () => {
    // Returning `{valid:false}` here would send an integrator hunting an attacker who does not
    // exist, while every genuine delivery is dropped.
    expect(() => verifyWebhookSignature({ ...base, secrets: {} })).toThrow(
      TypeError,
    );
  });

  test("a parsed body is refused outright", () => {
    expect(() =>
      verifyWebhookSignature({
        ...base,
        body: JSON.parse(genuine.body) as unknown as string,
      }),
    ).toThrow(TypeError);
  });

  test("a nonsensical tolerance is refused rather than silently widened", () => {
    expect(() =>
      verifyWebhookSignature({ ...base, toleranceSeconds: -1 }),
    ).toThrow(TypeError);
    expect(() =>
      verifyWebhookSignature({ ...base, toleranceSeconds: Number.NaN }),
    ).toThrow(TypeError);
  });
});
