"""The webhook verifier is only worth anything if it agrees with the signer, byte for byte.

So the bulk of this suite is not hand-written expectations: it is
``fixtures/webhook-signature-vectors.json``, generated by running Kaval's PRODUCTION signer
(``apps/server/src/webhooks/callback-signing.ts``) over bodies and key generations chosen to pin the
parts an independent reimplementation gets wrong — UTF-8 bodies, whitespace the sender did not
normalise, a rotation overlap, a sibling subscription's genuinely-signed delivery. The Node SDK runs
the same file. Two implementations that both pass it cannot disagree with each other, and neither can
drift away from the issuer without this failing.

The rest is the framework-shaped surface the vectors cannot express, and the caller mistakes that
must raise loudly rather than read as a forgery.
"""

import json
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import get_args

import pytest

import kaval
from kaval import (
    DEFAULT_WEBHOOK_TOLERANCE_SECONDS,
    WEBHOOK_SIGNED_CONTENT,
    WebhookRejectionReason,
    verify_webhook_signature,
)

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
FIXTURES = Path(__file__).resolve().parents[3] / "fixtures"
SUITE = json.loads((FIXTURES / "webhook-signature-vectors.json").read_text(encoding="utf-8"))
VECTORS = SUITE["vectors"]
BY_NAME = {vector["name"]: vector for vector in VECTORS}


def run(vector, **overrides):
    call = {
        "body": vector["body"],
        "headers": vector["headers"],
        "secrets": vector["secrets"],
        "tolerance_seconds": vector["tolerance_seconds"],
        "now": float(vector["now"]),
    }
    call.update(overrides)
    return verify_webhook_signature(**call)


def test_the_fixture_is_the_suite_it_claims_to_be():
    # A vector file that silently lost its negative half would still pass every case below.
    assert SUITE["signed_content"] == WEBHOOK_SIGNED_CONTENT
    assert len(VECTORS) >= 21
    assert len(BY_NAME) == len(VECTORS)
    assert sum(1 for v in VECTORS if v["expected"]["valid"]) >= 8
    assert sum(1 for v in VECTORS if not v["expected"]["valid"]) >= 13


@pytest.mark.parametrize("vector", VECTORS, ids=[v["name"] for v in VECTORS])
def test_conformance_with_the_issuers_signer(vector):
    result = run(vector)
    assert result.valid is vector["expected"]["valid"], vector["why"]
    # The dataclass is truthy exactly when it is valid, so the obvious spelling is the correct one.
    assert bool(result) is vector["expected"]["valid"]
    if result.valid:
        assert result.reason is None
        assert result.key_id == vector["headers"]["webhook-key-id"]
        assert result.webhook_id == vector["headers"]["webhook-id"]
        assert result.timestamp is not None and result.timestamp.tzinfo is not None
    else:
        assert result.reason == vector["expected"]["reason"], vector["why"]
        assert next(iter(vector["secrets"].values())) not in result.message


def test_a_reserialised_body_does_not_verify():
    # The mistake every webhook integration makes once: read `request.json`, then `json.dumps` it
    # back into the verifier. The parsed object is identical; the bytes are not, and no genuine
    # delivery would ever verify again.
    spaced = BY_NAME["valid_body_with_incidental_whitespace"]
    reserialised = json.dumps(json.loads(spaced["body"]))
    assert reserialised != spaced["body"]
    assert run(spaced).valid is True
    assert run(spaced, body=reserialised).valid is False


def test_raw_bytes_and_the_equivalent_text_are_the_same_input():
    delta = BY_NAME["valid_delta_event"]
    assert run(delta, body=delta["body"].encode("utf-8")).valid is True
    assert run(delta, body=bytearray(delta["body"].encode("utf-8"))).valid is True


def test_reads_headers_whose_names_were_not_lowercased():
    # `dict.get` is case-sensitive; a hand-built bag would otherwise read as an unsigned request.
    genuine = BY_NAME["valid_minimal"]
    titled = {name.title(): value for name, value in genuine["headers"].items()}
    assert "Webhook-Signature" in titled
    assert run(genuine, headers=titled).valid is True


def test_the_replay_window_defaults_to_five_minutes_with_an_inclusive_boundary():
    assert DEFAULT_WEBHOOK_TOLERANCE_SECONDS == 300
    genuine = BY_NAME["valid_minimal"]
    signed_at = float(genuine["headers"]["webhook-timestamp"])

    def at(offset):
        return run(
            genuine,
            tolerance_seconds=DEFAULT_WEBHOOK_TOLERANCE_SECONDS,
            now=signed_at + offset,
        )

    assert at(DEFAULT_WEBHOOK_TOLERANCE_SECONDS).valid is True
    assert at(DEFAULT_WEBHOOK_TOLERANCE_SECONDS + 1).valid is False
    assert at(-DEFAULT_WEBHOOK_TOLERANCE_SECONDS).valid is True
    assert at(-DEFAULT_WEBHOOK_TOLERANCE_SECONDS - 1).valid is False


def test_now_accepts_an_aware_datetime_and_defaults_to_the_wall_clock():
    genuine = BY_NAME["valid_minimal"]
    signed_at = datetime.fromtimestamp(
        float(genuine["headers"]["webhook-timestamp"]), tz=timezone.utc
    )
    assert run(genuine, now=signed_at + timedelta(seconds=299)).valid is True
    assert run(genuine, now=signed_at + timedelta(seconds=301)).valid is False
    # Not a tautology: the default has to be read at call time. A module-import `time.time()` would
    # pass every fixed-`now` test above and then start rejecting live traffic five minutes later.
    default_now = verify_webhook_signature(
        body=genuine["body"], headers=genuine["headers"], secrets=genuine["secrets"]
    )
    assert default_now.valid is False
    assert default_now.reason == "timestamp_out_of_tolerance"


def test_caller_mistakes_raise_instead_of_reading_as_a_forgery():
    genuine = BY_NAME["valid_minimal"]
    # Returning a rejection here would send an integrator hunting an attacker who does not exist,
    # while every genuine delivery is dropped.
    with pytest.raises(TypeError):
        run(genuine, secrets={})
    with pytest.raises(TypeError):
        run(genuine, body=json.loads(genuine["body"]))
    with pytest.raises(TypeError):
        run(genuine, tolerance_seconds=-1)
    with pytest.raises(TypeError):
        run(genuine, tolerance_seconds=float("nan"))


def test_the_verifier_is_exported_from_the_package_root():
    # The first thing a receiver needs must not require knowing a submodule path.
    for export in (
        "verify_webhook_signature",
        "WebhookSignatureResult",
        "WebhookRejectionReason",
        "WEBHOOK_SIGNED_CONTENT",
        "WEBHOOK_SIGNATURE_VERSION",
        "DEFAULT_WEBHOOK_TOLERANCE_SECONDS",
    ):
        assert export in kaval.__all__
        assert getattr(kaval, export) is not None


def test_every_rejection_reason_a_receiver_branches_on_is_documented():
    # The README lists the reasons inline so an integrator can write the branch without opening the
    # types. Renaming one silently is how that list becomes a lie.
    declared = set(get_args(WebhookRejectionReason))
    exercised = {v["expected"]["reason"] for v in VECTORS if v["expected"]["reason"]}
    assert exercised <= declared
    assert len(exercised) == 7
    readme = (PACKAGE_ROOT / "README.md").read_text(encoding="utf-8")
    for reason in declared:
        assert reason in readme, f"README omits {reason}"
    # `request.json` on this route is the one mistake that makes every genuine delivery fail.
    assert "await request.body()" in readme


def test_the_verifier_pulls_in_no_third_party_dependency():
    # It has to be usable in a receiver that never constructs a client, and it must never be the
    # reason a lambda cold-starts httpx.
    source = (Path(kaval.__file__).parent / "webhooks.py").read_text(encoding="utf-8")
    for forbidden in ("import httpx", "from httpx", "import requests", "urllib.request"):
        assert forbidden not in source
