"""Kaval Python SDK — verify the facts an AI agent's action relies on, with signed receipts."""

from importlib.metadata import PackageNotFoundError, version

from .client import (
    NO_TIMEOUT,
    KavalCancellationToken,
    KavalCancelledError,
    KavalClient,
    KavalError,
    KavalRetiredError,
    NoTimeout,
    OutcomeKind,
    RequestTimeout,
)
from .models import (
    FACT_STATE_DELTA_EVENT_TYPE,
    ActionContext,
    ActionDecision,
    ActionDisposition,
    ActionReversibility,
    AddSourceInput,
    AddSourceResult,
    CheckFact,
    CheckFreshnessFailure,
    CheckInput,
    CheckLatency,
    CheckMode,
    CheckReasonCode,
    CheckReceipt,
    CheckReceiptBasis,
    CheckReceiptFact,
    CheckResult,
    CheckSourceRef,
    CheckVerdict,
    ClaimInput,
    CreateWebhookInput,
    CreateWebhookResult,
    DecisionThreshold,
    EvidenceDocumentRef,
    EvidenceRef,
    FactBasisRef,
    FactStateDeltaEvent,
    FactStateTransition,
    FactStatus,
    Materiality,
    ProofPacket,
    RecompileSourceResult,
    RecordRef,
    SourceEventInput,
    SourceEventResult,
    StructuredClaim,
    VerifyInput,
    VerifyReceipt,
    VerifyResult,
    VerifyStatus,
    WatchedSource,
    WatchedSourceKind,
    WatchedSourceOrigin,
    WebhookSubscription,
    WebhookSubscriptionKind,
    WebhookVerification,
)

__all__ = [
    "FACT_STATE_DELTA_EVENT_TYPE",
    "NO_TIMEOUT",
    "ActionContext",
    "ActionDecision",
    "ActionDisposition",
    "ActionReversibility",
    "AddSourceInput",
    "AddSourceResult",
    "CheckFact",
    "CheckFreshnessFailure",
    "CheckInput",
    "CheckLatency",
    "CheckMode",
    "CheckReasonCode",
    "CheckReceipt",
    "CheckReceiptBasis",
    "CheckReceiptFact",
    "CheckResult",
    "CheckSourceRef",
    "CheckVerdict",
    "ClaimInput",
    "CreateWebhookInput",
    "CreateWebhookResult",
    "DecisionThreshold",
    "EvidenceDocumentRef",
    "EvidenceRef",
    "FactBasisRef",
    "FactStateDeltaEvent",
    "FactStateTransition",
    "FactStatus",
    "KavalCancellationToken",
    "KavalCancelledError",
    "KavalClient",
    "KavalError",
    "KavalRetiredError",
    "Materiality",
    "NoTimeout",
    "OutcomeKind",
    "ProofPacket",
    "RecompileSourceResult",
    "RecordRef",
    "RequestTimeout",
    "SourceEventInput",
    "SourceEventResult",
    "StructuredClaim",
    "VerifyInput",
    "VerifyReceipt",
    "VerifyResult",
    "VerifyStatus",
    "WatchedSource",
    "WatchedSourceKind",
    "WatchedSourceOrigin",
    "WebhookSubscription",
    "WebhookSubscriptionKind",
    "WebhookVerification",
]

try:
    # Single source of truth: read the installed distribution's version (set in pyproject.toml)
    # so __version__ can never drift from the package metadata / wheel filename.
    __version__ = version("kaval")
except PackageNotFoundError:  # running from source without an install
    __version__ = "0.0.0+unknown"
